apiVersion: apps/v1
kind: Deployment
metadata:
  name: connecting-memories
  labels:
    app: connecting-memories-backend
  namespace: student-f-arzt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: connecting-memories-backend
  template:
    metadata:
      labels:
        app: connecting-memories-backend
    spec:
      containers:
        - name: connecting-memories
          image: farzt/connecting-memories-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              protocol: TCP
          resources:
            limits:
              memory: "1Gi"
              cpu: "0.2"
            requests:
              memory: "500Mi"
              cpu: "0.1"
---
apiVersion: v1
kind: Service
metadata:
  name: connecting-memories-service
  namespace: student-f-arzt
spec:
  selector:
    app: connecting-memories-backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: connecting-memories-ingress
  namespace: student-f-arzt
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: "/$1"
spec:
  rules:
    - host: student.cloud.htl-leonding.ac.at
      http:
        paths:
          - path: /f.arzt/connecting-memories/(.*)$
            pathType: Prefix
            backend:
              service:
                name: connecting-memories-service
                port:
                  number: 3000