apiVersion: apps/v1
kind: Deployment
metadata:
   name: connecting-memories-pod
   labels:
      app: connecting-memories
spec:
   selector:
      matchLabels:
         app: connecting-memories
   template:
      metadata:
         labels:
            app: connecting-memories
      spec:
         containers:
         - name: connecting-memories
           image: farzt/connecting-memories-backend:latest
           imagePullPolicy: Always
           ports:
           - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: connecting-memories-service
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30000
  selector:
    app: connecting-memories