name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches:
      - github-actions

jobs:
  build_and_push:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build and push Docker image
        env:
          DOCKER_BUILDKIT: 1
        run: |
          cd Code/connecting-memories-server 
          docker build -t farzt/connecting-memories-backend .
          docker login -u farzt -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          docker push farzt/connecting-memories-backend:latest
      - name: Create Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: Code/connecting-memories-server/connecting-memories.yml
          tag: latest
          release_name: Release ${{ github.event.repository.updated_at }}
          overwrite: true
      - name: Upload Kubernetes File
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: Code/connecting-memories-server/connecting-memories-cloud.yml
          tag: latest
          overwrite: true
          prerelease: true