name: Docs

on:
  push:
    branches:
      - 'ascii-doctor-setup'
    paths:
      - asciidocs/**
  workflow_dispatch:

jobs:
  build:
    name: Build & Publish 🚀
    runs-on: ubuntu-latest
    env:
      INPUTPATH: asciidocs
      OUTPUTPATH: dist
      SLIDES: true
      BRANCH: gh-pages
    steps:
      - uses: actions/checkout@v4
      - name: Build
        uses: quirinecker/asciidoctor-convert-action@main
        with:
          slides: ${{ env.SLIDES }}
          inputPath: ${{ env.INPUTPATH }}
          outputPath: ${{ env.OUTPUTPATH }}
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          GITHUB_TOKEN: ${{ github.TOKEN }}
          BRANCH: ${{ env.BRANCH }}
          FOLDER: ${{ env.OUTPUTPATH }}
          
  build-and-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      #- name: Deploy to github 🚀
      #  uses: JamesIves/github-pages-deploy-action@4.1.0
      #  with:
      #    branch: gh-pages # The branch the action should deploy to.
      #    folder: build # The folder the action should deploy.

      # Includes the AsciiDoctor GitHub Pages Action to convert adoc files to html and publish to gh-pages branch
      # https://github.com/manoelcampos/asciidoctor-ghpages-action/blob/main/.github/workflows/asciidoctor-ghpages.yml
      - name: asciidoctor-ghpages
        uses: manoelcampos/asciidoctor-ghpages-action@v2
        with:
          #asciidoctor_params: --attribute=nofooter
          asciidoctor_params: -r asciidoctor-diagram -a icons=font -a revealjs_theme=white -a source-highlighter=rouge -a imagesdir=images -a revealjs_slideNumber=c/t -a revealjs_transition=slide -a revealjs_hash=true -a sourcedir=src/main/java
          #pdf_build: true
          slides_build: true
          slides_main_adoc_file: asciidocs-slides/index
          slides_skip_asciidoctor_build: true
